title: Yugandhar Naidu
logo: https://github.com/Yugandhar0530/Yugandhar_Portfolio/blob/main/assets/yugandhar_photo.png
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
